### PR TITLE
add MIT license and slight README.md correction to number of parallel jobs.

### PR DESCRIPTION
**Pull request by TheHeroBrine422**

### CODE REVIEW

**Comment by TheHeroBrine422** [comment]
This should also probably be included in an issue, but when transferring a large amount of data line 52 appears to have issues doing the math it needs to do. I am transferring roughly 1.7TB of files and got this error:

`./prsync: line 52: 1.76084e+12: syntax error: invalid arithmetic operator (error token is ".76084e+12")`

**Comment by nathanhaigh** [comment]
> This should also probably be included in an issue, but when transferring a large amount of data line 52 appears to have issues doing the math it needs to do. I am transferring roughly 1.7TB of files and got this error:
> 
> `./prsync: line 52: 1.76084e+12: syntax error: invalid arithmetic operator (error token is ".76084e+12")`

I think this depends on the version of awk being used. In any case its easily fixable using a `printf`. 

Thanks for the PR, I'll review it shortly.

**Comment by TheHeroBrine422** [comment]
The line 52 issue really isn't a big deal. The script continues running even with the error and it appears to just be a info/debug message that lists the total size of all files being transferred.

**Comment by nathanhaigh** [comment]
I've now rolled these changes into `main`. Thanks for the PR!

**Pull request closed without merging**
